# Generated by Django 5.2.6 on 2025-09-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('outdoor', 'Outdoor Items'), ('indoor', 'Indoor Items')], max_length=50),
        ),
    ]
